Rest
GoncharukAD/TestGuru pull request #10
Opened 2022-09-16 18:38 UTC by GoncharukAD

Install Webpacker and add Question controller and routes

2022-09-17 15:58 UTC, VidgarVii requested changes

2022-09-17 15:58 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie)

2022-09-17 15:58 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/test_id/questions" method="post">
тут опечатка. Нет такого пути /tests/test_id/questions

2022-09-17 15:58 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +</form>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-09-17 15:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_question
не в каждом экшане нужен вопрос. Тем более не везде приходит параметр с id

2022-09-17 15:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
пересмотри урок.
Сначала вытаскиваем ресурс из базы. Затем только показываем его пользователю. А не на оборот. И делаем это 1 раз. А тут почему-то 2 вызова render

2022-09-17 15:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.create(
данный экшен должен только показать страницу формы создания вопроса, а не создавать вопрос. Создание вопроса происходит в экшане create

2022-09-17 15:58 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.create(
и еще нужно проверять сохранен ли объект.
Если сохранен, то редиректим нужную страницу
если нет, то рендерим форму заново. 
В объекте вопроса будут сохранены ошибки валидации, которые в будущем покажем пользователю

2022-09-18 12:26 UTC, GoncharukAD commented on config/routes.rb
> +    resources :questions
Добавил  в tests

2022-09-18 12:27 UTC, GoncharukAD commented on app/views/questions/new.html.erb
> +<form action="/tests/test_id/questions" method="post">
Не дописал формат,поправлю
 POST   /tests/:test_id/questions(.:format)                                                               questions#create

2022-09-18 12:39 UTC, GoncharukAD commented on app/controllers/questions_controller.rb
> +  before_action :find_question
Добавил ограничение,чтобы работал только для destroy и show

2022-09-20 05:20 UTC, VidgarVii requested changes

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
в этом проекте будем использовать только 1 формат ответа.

2022-09-20 05:20 UTC, VidgarVii commented on config/routes.rb
> +  resources :tests, shallow: true do
тут прям сильно промахнулся) Почитай для чего и как используется опция shallow

2022-09-20 05:20 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/test_id/questions(.:format)" method="post">
я уже писал. Нет такого пути /tests/test_id/questions
(.:format) - лишнее.
проверяй код прежде чем сдавать на проверку

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      @test = Question.find(params[:test_id])
1 этого кода не должно быть в мастер ветке!
2 тут путаница в параметрах
Какое отношение параметр test_id имеет для вопроса?

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Test.find(params[:test_id]).questions.find(params[:id])
чтобы найти 1 вопрос, не нужен тест. Достаточно знать ид самого вопроса

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if question.save!
1 тут происходит двойная попытка создания вопроса. 
2 тут баг
3 нельзя использовать bang! метод если хотим вернуть не валидный объект юзеру для редактирования

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    end
после создания ресурса по REST надо вернуть юзеру этот ресурс. В данном случаи надо отправить юзера на страницу show
А вот если ресурс не был создан из-за ошибок в параметрах, то надо от рендерить ему форму, а не просто вызвать метод new. Экшаны так не вызывают

2022-09-20 05:20 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :test_id)
`test_id` не нужно в разрешенных параметрах в явном виде указывать
этот параметр не передается под ключом `question`, как ты здесь указал, он идет в основном теле параметров наравне с ключом `question` (посмотри в лог сервера)

также посмотри в форму - там тоже нет ничего похожего на `<input type="text" name="question[test_id]" id="question-test_id">`

2022-10-18 10:56 UTC, VidgarVii requested changes

2022-10-18 10:56 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
ниже есть колбек который ищет нужный вопрос. Почини его и пользуйся

2022-10-18 10:56 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @questions = Test.find(params[:test_id]).questions
запросы в базу которые дублируются стоит вынести в колбеки
Test.find(params[:test_id])
Question.find(params[:id])

2022-10-18 10:56 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
здесь будет создан вопрос, без привязки к тесту
даже правильней сказать будет попытка создать вопрос
потому что если в модели `Question` есть строка `belongs_to :test`, то рельсы не разрешат его создать без указания валидного `test_id`

2022-10-18 10:56 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if @question.save
строчкой выше вызывается ceate
А тут save
Если в 1 раз объект не записался, то save не исправит это положение. Надо 1 раз проверять записался ли ресурс в базу
Я хочу сказать что использование create не верно

2022-10-18 10:56 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      @question.show
что тут происходит?

2022-10-18 10:56 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/test_id/questions" method="post">
ссылка не верная.
Тестируй код!

2022-10-18 13:24 UTC, GoncharukAD commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Да,тут двойной поиск был,т.к. в колбеке указао,чтобы он для этой функции использовлся

2022-10-18 13:24 UTC, GoncharukAD commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Да,тут двойной поиск был,т.к. в колбеке указао,чтобы он для этой функции использовлся

2022-10-18 13:35 UTC, GoncharukAD commented on app/views/questions/new.html.erb
> +<form action="/tests/test_id/questions" method="post">
/tests/:test_id/questions корректно.
Хотя сама форма открывалась(

2022-10-19 06:13 UTC, VidgarVii requested changes

2022-10-19 06:13 UTC, VidgarVii commented on README.md
> +* Публикация результатов
нет такой сущности

2022-10-19 06:13 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      render action: "show"
тут надо сделать именно редирект на страницу show
Посмотри отличие редирект и рендер

2022-10-19 06:13 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question.destroy
после удаления надо юзера куда-то отправить

2022-10-19 06:13 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/:test_id/questions" method="post">
тестируй создание вопроса

2022-10-21 14:52 UTC, merged