Add view for tests and questions
GoncharukAD/TestGuru pull request #11
Opened 2022-10-26 12:45 UTC by GoncharukAD

2022-10-27 05:52 UTC, VidgarVii requested changes

2022-10-27 05:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    def index
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-10-27 05:52 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  skip_before_action :find_test, only: %i[index new create]
очень плохой подход. Сначала у тебя идёт вызов колбека для всех экшенов. А ниже запрет этого же колбека. Тоже самое что выкопать большую яму, а потом её на половину закопать.
Лучше было бы сразу объявить список экшенов где нужно использовать колбек

2022-10-27 05:52 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @new_test = Test.new(question_params)
протестируй создание теста. Уверен что не будет работать

2022-10-27 05:52 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @new_test = Test.new(question_params)
обычно принято называть переменную просто @test
А состояние объекта скажут его атрибуты и методы

2022-10-27 05:52 UTC, VidgarVii commented on app/helpers/footer_helper.rb
> +end
это мы уже проходили(
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2022-10-27 05:52 UTC, VidgarVii commented on app/views/tests/_test.html.erb
> +  <<td><%= link_to 'Delete', test_path(test.id), method: :delete %></td>>
протестируй работоспособность

2022-10-27 05:52 UTC, VidgarVii commented on app/views/tests/show.html.erb
> +
нет списка вопросов

2022-10-27 09:23 UTC, GoncharukAD commented on app/helpers/footer_helper.rb
> +end
Да,это косяк,про который я не заметил,буду внимательней(

2022-10-28 03:35 UTC, VidgarVii requested changes

2022-10-28 03:35 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test = Test.new(test_params)
https://github.com/GoncharukAD/TestGuru/pull/11#discussion_r1006426838

2022-10-28 03:35 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +<tr>
https://github.com/GoncharukAD/TestGuru/pull/11#discussion_r1006427591
Проверь ВЕСЬ рекверст. Везде должно быть исправлено

2022-10-28 10:45 UTC, merged