Autentifications
GoncharukAD/TestGuru pull request #13
Opened 2022-11-10 15:04 UTC by GoncharukAD

Authentification,Registration and Flash

2022-11-11 05:17 UTC, VidgarVii requested changes

2022-11-11 05:17 UTC, VidgarVii commented on app/assets/stylesheets/nav.scss
> +}
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +
лишний отступ. Используй рубокоп

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
У тебя сейчас каждый раз для залогиненного юзера перезаписывается его email и ИД?
И почему это делается тут, если это вообще требуется?
Ведь cookies[:email] и cookies[:id] даже не используешь в дальнейшем.
Задача данного метода не пускать не залогиненного юзера совершать действия и отправлять его на страницу логина

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:start_page] || root_path
не вижу чтобы где-то устанавливалась кука start_page.
И данная запись нужна только после логина. Соответственно хорошо бы её сразу удалять

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +  def new
def new; end

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +
не понимаю, зачем везде вставлять этот отступ. Ни кто так код не пишет

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>      @user.tests.push(@test)
обрати внимание, что в этом задании был добовлен метод current_user

2022-11-11 05:17 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>      @user.tests.push(@test)
так же этого current_user можно исползовать при создании теста

2022-11-11 05:17 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +    if flash[:alert]
здесь более правильно было бы принимать в аргументах `type`
потому что флеш-сообщения могут быть разных типов, а этот хелпер вернет сообщение, только если это `:alert

2022-11-11 05:17 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +end
No new lina at end of file

2022-11-11 05:17 UTC, VidgarVii commented on app/models/test_passage.rb
> +      correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
разбери что делает это код и метод to_a
И зачем тут проверка answer_ids.nil?

2022-11-11 05:17 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +    <% end %>
будет чище, если шапку вынести в отдельный паршал

2022-11-11 05:18 UTC, VidgarVii requested changes

2022-11-11 05:18 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +    <% end %>
а где кнопки логина и решистрации?

2022-11-11 06:13 UTC, GoncharukAD commented on app/models/test_passage.rb
> +      correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
Так,to_a тут лишнее,т.к. answerd_ids и так приходит в виде массива.
Проверка answer_ids.nil? нужна для того,чтобы если пользователь ничего не выберет и придет пустой массив,не появлялась ошибка

2022-11-11 06:34 UTC, GoncharukAD commented on app/views/layouts/application.html.erb
> +    <% end %>
Про паршал сделаю.
Кнопки логина и регистрации в _form в sessions

2022-11-11 06:41 UTC, GoncharukAD commented on app/controllers/tests_controller.rb
>      @user.tests.push(@test)
Здесь почему надо поменять я понял,а вот про создание теста где использовать-не понял.Возможно вы имеете в виду автора,но авторство мы еще не добавляли

2022-11-11 14:13 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:start_page] = request.original_url
данная запись нужна только для не залогиненного юзера. 
Каждый раз переписывать start_page для залогиненных юзеров нет смысла

2022-11-11 14:14 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +     content_tag :p, flash[:type], class: 'flash alert'
отступ должен быть в 2 пробела. не 1
используй рубокоп

2022-11-11 14:15 UTC, VidgarVii commented on app/views/questions/_question.html.erb
>  </li>
No new line
Проверь везде. Даже гитхаб ругается

2022-11-11 14:20 UTC, VidgarVii commented on app/models/test_passage.rb
> +      correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
метод to_a как раз решает проблему пустого answer_ids
nil.to_a => []
А вот if answer_ids.nil? false
становится многословным и не нужным
вообще можно было записать так 
`answer_ids && correct_answers.ids.sort == answer_ids.map(&:to_i).sort`
Но с to_a самый короткий вариант

2022-11-11 14:23 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>      @user.tests.push(@test)
как это не добовляли?  А это что?)
https://github.com/GoncharukAD/TestGuru/blob/Autentifications/app/models/test.rb#L5
Протестируй экшен создания теста. Полагаю он не работает

2022-11-12 11:56 UTC, VidgarVii requested changes

2022-11-12 11:56 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:start_page] = request.original_url
внутри условных операторов нужны отступы
```
unless current_user
  cookies[:start_page] = request.original_url
  ...
end
```

2022-11-12 11:56 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:start_page] || root_path
Вот здесь можно сразу удалить данные из кук. delete возвращает значение, которое удалил

```ruby
def destination_path
  cookies.delete(:redirect_path) || root_path
end
```

2022-11-12 11:56 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    end
а как дела обстоят с созданием теста? Кто там автор?

2022-11-12 11:56 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +    content_tag :p, flash[:type], class: 'flash alert' if flash[:type]
:type это новый тип флеша? Не вижу чтобы он где-то использовался. 
И как это связанно с называнием метода?
И в css почему класс устанавливается alert а не type

2022-11-12 11:56 UTC, VidgarVii commented on app/views/shared/_logged_in.html.erb
> +
!

2022-11-12 13:24 UTC, GoncharukAD commented on app/controllers/tests_controller.rb
>      @user.tests.push(@test)
Все,понял,поправил.Создание теста работает

2022-11-13 10:14 UTC, VidgarVii requested changes

2022-11-13 10:14 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.author = current_user
используй методы ассоциаций. Все можно сделать за 1 строчку
`@test = current_user.authored_tests.build(test_params)`

2022-11-13 10:14 UTC, VidgarVii commented on app/helpers/flash_helper.rb
> +  end
суть хелпера для флеш, чтобы заменить паршал.
Хелпер должен возвращать хтмл с определенным типом флеш сообщения
соответственно для каждого типа должен проставляться свой css класс
как раз это и обсуждали

2022-11-13 10:14 UTC, VidgarVii commented on app/models/test_passage.rb
> +    answer_ids && correct_answers.ids.sort == answer_ids.map(&:to_i).sort
поставь to_a
чтобы метод мог возвращать только true/false

2022-11-14 03:48 UTC, VidgarVii requested changes

2022-11-14 03:48 UTC, VidgarVii commented on app/models/test_passage.rb
> +    answer_ids && correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
что тут происходит? разберись в коде!
я иммел ввиду поставить to_a вместо answer_ids &&

2022-11-14 11:46 UTC, merged