Add JavaScript
GoncharukAD/TestGuru pull request #18
Opened 2022-12-13 08:23 UTC by GoncharukAD

Add JS sort and password match

2022-12-14 04:57 UTC, VidgarVii requested changes

2022-12-14 04:57 UTC, VidgarVii commented on app/frontend/packs/utilities/sorting.js
> +  var control = document.querySelector('.sort-by-title');
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2022-12-14 04:57 UTC, VidgarVii commented on app/frontend/packs/utilities/sorting.js
> +}
лучше потренироваться в ООП. JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2022-12-20 19:04 UTC, closed without merging

2022-12-20 19:04 UTC, GoncharukAD commented
Old pull request,with JS error